/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;

import java.sql.SQLException;
import Class.Apstraktne.AbstractDAO;
import Class.KlaseBaze.KeseProba;
import Class.KlaseBaze.KutijaProba;
import Class.KlaseBaze.Partneri;
import java.awt.AWTException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nebojsa
 */
public class FormGlavna extends javax.swing.JFrame {

    /**
     * Creates new form Glavna
     */
    public FormGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Partneri = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proizvodnja Kesa");

        jMenuBar1.setToolTipText("");

        jMenu1.setText("Osnovni podaci");

        jMenuItem3.setActionCommand("Kese");
        jMenuItem3.setLabel("Kese");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKeseUniverzalno(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Kutije");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFormKutije(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        Partneri.setText("Partneri");
        Partneri.setActionCommand("Partneri");
        Partneri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartneriActionPerformed(evt);
            }
        });
        jMenu1.add(Partneri);
        Partneri.getAccessibleContext().setAccessibleName("Partneri");

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JFormKutije(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFormKutije
        FormForme f = null;
        AbstractDAO klasa;
        klasa = new KutijaProba();
        try {
            f = new FormForme(this, "KUTIJE PROBA SA FRAME-ovima", 0.99, "");
            f.k = klasa;
            f.main();
        } catch (SQLException | ParseException | AWTException ex) {
            Logger.getLogger(FormGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JFormKutije

    private void JKeseUniverzalno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKeseUniverzalno
        FormForme f = null;
        AbstractDAO klasa;
        klasa = new KeseProba();
        try {
            f = new FormForme(this, "KESE PROBA BEZ FRAME-ova",0.6, "");
            f.k = klasa;
            f.main();
        } catch (SQLException | ParseException | AWTException ex) {
            Logger.getLogger(FormGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JKeseUniverzalno

    private void PartneriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartneriActionPerformed
        FormForme f = null;
        AbstractDAO klasa;
        klasa = new Partneri();
        try {
            f = new FormForme(this, "PARTNERI", 0.9, "");
            f.k = klasa;
            f.main();
        } catch (SQLException | ParseException | AWTException ex) {
            Logger.getLogger(FormGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PartneriActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Partneri;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
